# Generated by Django 4.1.2 on 2022-10-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
